---
title: "CodeBook"
author: "Sydney Winner"
date: "2026-05-21"
output: html_document
---

## Variables

-   TimeBodyAccelerometer.mean...X

-   TimeBodyAccelerometer.mean...Y

-   TimeBodyAccelerometer.mean...Z

-   TimeBodyAccelerometer.std...X

-   TimeBodyAccelerometer.std...Y

-   TimeBodyAccelerometer.std...Z

-   TimeGravityAccelerometer.mean...X

-   TimeGravityAccelerometer.mean...Y

-   TimeGravityAccelerometer.mean...Z

-   TimeGravityAccelerometer.std...X

-   TimeGravityAccelerometer.std...Y

-   TimeGravityAccelerometer.std...Z

-   TimeBodyAccelerometerJerk.mean...X

-   TimeBodyAccelerometerJerk.mean...Y

-   TimeBodyAccelerometerJerk.mean...Z

-   TimeBodyAccelerometerJerk.std...X

-   TimeBodyAccelerometerJerk.std...Y

-   TimeBodyAccelerometerJerk.std...Z

-   TimeBodyGyroscope.mean...X

-   TimeBodyGyroscope.mean...Y

-   TimeBodyGyroscope.mean...Z

-   TimeBodyGyroscope.std...X

-   TimeBodyGyroscope.std...Y

-   TimeBodyGyroscope.std...Z

-   TimeBodyGyroscopeJerk.mean...X

-   TimeBodyGyroscopeJerk.mean...Y

-   TimeBodyGyroscopeJerk.mean...Z

-   TimeBodyGyroscopeJerk.std...X

-   TimeBodyGyroscopeJerk.std...Y

-   TimeBodyGyroscopeJerk.std...Z

-   TimeBodyAccelerometerMagnitude.mean

-   TimeBodyAccelerometerMagnitude.std

-   TimeGravityAccelerometerMagnitude.mean

-   TimeGravityAccelerometerMagnitude.std

-   TimeBodyAccelerometerJerkMagnitude.mean

-   TimeBodyAccelerometerJerkMagnitude.std

-   TimeBodyGyroscopeMagnitude.mean

-   TimeBodyGyroscopeMagnitude.std

-   TimeBodyGryoscopeJerkMagnitude.mean

-   TimeBodyGryoscopeJerkMagnitude.std

-   FrequencyBodyAccelerometer.mean...X

-   FrequencyBodyAccelerometer.mean...Y

-   FrequencyBodyAccelerometer.mean...Z

-   FrequencyBodyAccelerometer.std...X

-   FrequencyBodyAccelerometer.std...Y

-   FrequencyBodyAccelerometer.std...Z

-   FrequencyBodyAccelerometer.meanFreq...X

-   FrequencyBodyAccelerometer.meanFreq...Y

-   FrequencyBodyAccelerometer.meanFreq...Z

-   FrequencyBodyAccelerometerJerk.mean...X

-   FrequencyBodyAccelerometerJerk.mean...Y

-   FrequencyBodyAccelerometerJerk.mean...Z

-   FrequencyBodyAccelerometerJerk.std...X

-   FrequencyBodyAccelerometerJerk.std...Y

-   FrequencyBodyAccelerometerJerk.std...Z

-   FrequencyBodyAccelerometerJerk.meanFreq...X

-   FrequencyBodyAccelerometerJerk.meanFreq...Y

-   FrequencyBodyAccelerometerJerk.meanFreq...Z

-   FrequencyBodyGyroscope.mean...X

-   FrequencyBodyGyroscope.mean...Y

-   FrequencyBodyGyroscope.mean...Z

-   FrequencyBodyGyroscope.std...X

-   FrequencyBodyGyroscope.std...Y

-   FrequencyBodyGyroscope.std...Z

-   FrequencyBodyGyroscope.meanFreq...X

-   FrequencyBodyGyroscope.meanFreq...Y

-   FrequencyBodyGyroscope.meanFreq...Z

-   FrequencyBodyAccelerometerMagnitude.mean

-   FrequencyBodyAccelerometerMagnitude.std

-   FrequencyBodyAccelerometerMagnitude.meanFreq

-   FrequencyBodyAccelerometerJerkMagnitude.mean

-   FrequencyBodyAccelerometerJerkMagnitude.std

-   FrequencyBodyAccelerometerJerkMagnitude.meanFreq

## Data

Human Activity Recognition Using Smartphones: <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>

## Modifications

-   Merged test and train data sets into one set (tidy)

-   Output only mean and standard deviations of variables

-   Renamed activity names in data set

-   Created second data set with averages of each variable (tidy2)
